name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build and run tests
      run: make check
    - name: make clean
      run: make clean
    - name: cmake
      run: cmake ./
    - name: make
      run: make
    - name: run tests
      run: ./tests
